### ISSUE TITLE
Wasm-pack errors originating from `contrib/test.sh` are swallowed in CI 

### ISSUE THREAD

**Issue by rishflab** [ElementsProject/rust-secp256k1-zkp#26]
If I perform a  [failing `curl` command](https://github.com/ElementsProject/rust-secp256k1-zkp/pull/25/commits/e1e86ffeac0b0324175bfd421e10c4bf1f2d54d6) in the  `contrib/test.sh` script the error is caught in CI and the CI run fails. 

This is not the case for errors that occur when `wasm-pack build && wasm-pack test` is called. Those errors are swallowed for some reason.

Adding `set -e` to the top of the script does nothing.

**Comment by jonasnick** [comment]
Fixed by #25. Thanks @rishflab
