### ISSUE TITLE
Upgrade at least to `rust-secp256k1` 0.21

### ISSUE THREAD

**Issue by thomaseizinger** [ElementsProject/rust-secp256k1-zkp#32]
The 0.21 release will include https://github.com/rust-bitcoin/rust-secp256k1/pull/326 which is required for interoperability with the `ThirtyTwoByteHash` trait. In order to use `rust-secp256k1-zkp` in a project together with `rust-secp256k1` 0.21, we will need to bump the version we are depending on and release a new version as well.

**Comment by thomaseizinger** [comment]
Looks like we have a release: https://github.com/rust-bitcoin/rust-secp256k1/pull/347

**Comment by apoelstra** [comment]
We need to do a point release (probably today) beacuse we added a new type but forgot to export it publicly.

**Comment by thomaseizinger** [comment]
Yeah I saw that. Shouldn't matter much for this repository though because we don't pin the version to the patch release so I am going to go ahead and prepare a patch to bump to 0.21.
