### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Tibo-lg** [ElementsProject/rust-secp256k1-zkp#40]
I would really love to have a new release that includes #39 so that I could have my project completely free of github dependencies and make a proper release of it. I also depend on the added serde serialization for `EcdsaAdaptorSignature`. I think that those two changes are non breaking and so I'm happy to prepare  a branch with only those two for a 0.4.1 release if people think it's a good way to go. I'm also happy with a 0.5.0 release based on master if people prefer that (as I believe the two renames are breaking).

Let me know if there is anything I could help with to make that happen.

**Comment by jonasnick** [comment]
needs #42 still

**Comment by jonasnick** [comment]
done!

**Comment by Tibo-lg** [comment]
Thanks @jonasnick!
