### ISSUE TITLE
Unable to find library `-llog` building for android

### ISSUE THREAD

**Issue by RCasatta** [ElementsProject/rust-secp256k1-zkp#51]
```
   = note: /usr/bin/ld: cannot find -llog: No such file or directory
          collect2: error: ld returned 1 exit status
```

to reproduce

download and unzip android ndk 23c https://developer.android.com/ndk/downloads#lts-downloads
```
rustup target add i686-linux-android

export NDK=/path/to/android-ndk-r23c/
export HOST=linux-x86_64

export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/$HOST
export PATH=$PATH:$TOOLCHAIN/bin

export CC=i686-linux-android21-clang
export AR=llvm-ar
cargo build --target i686-linux-android
```

Note, this build works for https://github.com/rust-bitcoin/rust-secp256k1 and also  version `0.4.0` of this lib doesn't have this error

(to successfully build on `0.4.0`,  `secp256k1-sys` must be pinned -> `secp256k1-sys = "=0.4.1"`

**Comment by apoelstra** [comment]
I don't know what to make of this. This library does not depend on `log` anywhere and I don't know where that `-llog` line would come from.

**Comment by RCasatta** [comment]
Thanks for having a look, I'll close for now since maybe it's not an issue of this repo but something else
