### ISSUE TITLE
Cannot build latest tag `0.5.0`

### ISSUE THREAD

**Issue by RCasatta** [ElementsProject/rust-secp256k1-zkp#52]
This fixes if we want to release 0.5.1

(FYI the error is also on the other tagged version but the `0.1.0`)

```
diff --git a/Cargo.toml b/Cargo.toml
index 47b2b6f..d9b0d66 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -31,6 +31,7 @@ use-rand = ["rand", "secp256k1/rand"]
 
 [dependencies]
 secp256k1 = "0.20.0"
+secp256k1-sys = "=0.4.1"
 secp256k1-zkp-sys = { version = "0.5.0", default-features = false, path = "./secp256k1-zkp-sys" }
 rand = { version = "0.6", default-features = false, optional = true }
 serde = { version = "1.0", default-features = false, optional = true }
```

**Comment by apoelstra** [comment]
I think we should just drop our explicit `Hash` impl rather than pinning secp-sys.

**Comment by RCasatta** [comment]
yeah right, sorry, what maybe what is needed is a point release (`0.5.1`) which is tag `0.5.0` + https://github.com/ElementsProject/rust-secp256k1-zkp/commit/3db533c38ff8fc393719daf329ae9ebb44f019d0  

Or a `0.6.0` release with current master

The pinning secp-sys is an hack I am using in a downstream lib

**Comment by apoelstra** [comment]
I'm a bit confused what you mean by "a `0.6.0` release with current master" ... AFAICT such a release has been out for a month.

I can backport a fix though for 0.5.1.

**Comment by apoelstra** [comment]
Ah, I understand, rust-secp-zkp*-sys* is not at 0.6.0. Oops.

**Comment by apoelstra** [comment]
No, it is. @RCasatta are you able to bump to 0.6.0 or would you like me to create a 0.5.1?

**Comment by RCasatta** [comment]
Sorry, I wrongly assumed 0.6.0 wasn't released because I didn't see a tag.

**Comment by apoelstra** [comment]
Sorry, it looks like I forgot to push the tag (it was there locally, which is why I couldn't figure out the problem).

I've pushed it, things should be good now.

**Comment by RCasatta** [comment]
All good! Thanks
